# Generated by Django 2.2.13 on 2021-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('pwd', models.CharField(max_length=120)),
                ('login', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='address',
        ),
        migrations.RemoveField(
            model_name='login',
            name='city',
        ),
        migrations.RemoveField(
            model_name='login',
            name='login',
        ),
        migrations.RemoveField(
            model_name='login',
            name='state',
        ),
    ]
