# Generated by Django 3.1.5 on 2021-01-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20210124_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_ewaste',
            name='Mob_number',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='add_ewaste',
            name='Ward',
            field=models.CharField(max_length=120),
        ),
    ]
