# Generated by Django 3.1.5 on 2021-01-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20210124_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_ewaste',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='add_ewaste',
            name='description',
        ),
    ]
