# Generated by Django 3.1.5 on 2021-01-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20210124_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_ewaste',
            name='Price',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='add_ewaste',
            name='description',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
